#!/usr/bin/env python3
"""
Generates world/climate.yaml: night rain limits on Weather_3.9's climate (juninho-weather, def/climate/default),
as edits of the merged file (megapack `base_edits`; the path's winner is Weather's copy).

Weather_3.9 makes night rain far foggier and wetter than vanilla (fog density up to 0.047 from 6.9 m, wetness
mostly 0.95), and its fair-weather climate adds drizzle variants with fog from 6.9 m. With night fog colours near
black, the far end and the edges of the headlight beam fade out: the beam looks shorter, narrower and darker.

For every sun profile at night (low_elevation <= NIGHT_MAX_ELEVATION) and every weather variant that rains
(rain_intensity > 0), each value is only ever made less severe:
  fog_density      lowered to FOG_DENSITY_MAX
  fog_offset       (distance where fog starts) raised to FOG_OFFSET_MIN
  rain_max_wetness lowered to WETNESS_MAX
Dry variants (including pure fog weather) and daytime/twilight profiles are left as Weather made them. The
starting values are about vanilla 1.61's night rain; tune them after play tests.

usage: python tools/night_climate.py [--check]    (--check: fail if world/climate.yaml would change)
"""
from __future__ import annotations

import argparse
import pathlib
import re
import struct
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILL = pathlib.Path.home() / ".agent-brains/profiles/ets2-mod-developer/skills/megapack/scripts"
sys.path.insert(0, str(SKILL))
from megapack import host_section  # noqa: E402
from siiedit import SiiFile  # noqa: E402

OUT = ROOT / "world" / "climate.yaml"
SOURCE = "juninho-weather"
FILES = ["def/climate/default/nice.sii", "def/climate/default/bad.sii"]

NIGHT_MAX_ELEVATION = -4.0   # sun at or below 4 degrees under the horizon
FOG_DENSITY_MAX = 0.005      # vanilla night rain: ~0.0032-0.0037
FOG_OFFSET_MIN = 25.0        # vanilla night rain: 8.6-37.5 m, mostly 27.5-33 m
WETNESS_MAX = 0.6            # vanilla night rain: 0.16-1.0, weighted average 0.53
INDEXED = re.compile(r"^(\w+)\[(\d+)\]$")


def num(v: str) -> float:
    v = v.strip()
    return struct.unpack(">f", bytes.fromhex(v[1:]))[0] if v.startswith("&") else float(v)


def fmt(x: float) -> str:
    return f"{x:.6g}"


def source_dir() -> pathlib.Path:
    ref_root = pathlib.Path(host_section("Extracted Reference Root")["root"])
    src = yaml.safe_load((ROOT / "sources.yaml").read_text(encoding="utf-8"))["sources"]
    s = next(s for s in src if s["id"] == SOURCE)
    d = ref_root / "workshop" / str(s["workshop"]) / str(s["version"])
    if not d.is_dir():
        sys.exit(f"missing extraction {d} — run extract-reference first")
    return d


def arrays(sii: SiiFile, unit: str) -> dict[str, dict[int, str]]:
    out: dict[str, dict[int, str]] = {}
    for _, key, val in sii.units[unit].attrs:
        m = INDEXED.match(key)
        if m:
            out.setdefault(m.group(1), {})[int(m.group(2))] = val
    return out


def limits(src: pathlib.Path) -> tuple[dict, list[str]]:
    edits: dict = {}
    report: list[str] = []
    for rel in FILES:
        sii = SiiFile.read(src / rel)
        night = [u for u in sii.order if sii.units[u].type == "sun_profile"
                 # elevations are stored as floats such as -3.9999986 for -4
                 and round(num(sii.values(u, "low_elevation")[0]), 3) <= NIGHT_MAX_ELEVATION]
        changed = 0
        for unit in night:
            a = arrays(sii, unit)
            ops: dict[str, str] = {}
            for i, rain in sorted(a["rain_intensity"].items()):
                if num(rain) <= 0:
                    continue
                if num(a["fog_density"][i]) > FOG_DENSITY_MAX:
                    ops[f"fog_density[{i}]"] = fmt(FOG_DENSITY_MAX)
                if num(a["fog_offset"][i]) < FOG_OFFSET_MIN:
                    ops[f"fog_offset[{i}]"] = fmt(FOG_OFFSET_MIN)
                if num(a["rain_max_wetness"][i]) > WETNESS_MAX:
                    ops[f"rain_max_wetness[{i}]"] = fmt(WETNESS_MAX)
            if ops:
                edits.setdefault(rel, {})[unit] = {"set": ops}
                changed += len(ops)
        report.append(f"{rel}: {len(night)} night profiles, {len(edits.get(rel, {}))} edited, {changed} values")
    return edits, report


def render(edits: dict) -> str:
    head = (
        "# GENERATED by tools/night_climate.py — do not edit by hand; change the script and rerun it.\n"
        f"# Night rain limits on Weather_3.9's climate (sun <= {NIGHT_MAX_ELEVATION} deg, raining variants only):\n"
        f"# fog_density <= {FOG_DENSITY_MAX}, fog_offset >= {FOG_OFFSET_MIN} m, rain_max_wetness <= {WETNESS_MAX}.\n")
    body = yaml.safe_dump({k: edits[k] for k in sorted(edits)}, sort_keys=False, allow_unicode=True, width=10_000)
    return head + body


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    edits, report = limits(source_dir())
    for r in report:
        print(r)
    text = render(edits)
    if args.check:
        same = OUT.is_file() and OUT.read_text(encoding="utf-8") == text
        print(f"{OUT.relative_to(ROOT)} {'up to date' if same else 'OUT OF DATE'}")
        return 0 if same else 1
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
