#!/usr/bin/env python3
"""
Generates world/signs.yaml: drops the LOD models of base-game signs that are also instanced, as edits of the
current base game (megapack `base_edits`).

The engine draws an instanced sign without LODs and logs `Lodding of instanced sign is not supported! (<unit>)`
for every placed copy (170 lines per drive through Spain on 1.61). In 1.61.1.1 five units carry both
`instanced: true` and `dynamic_lod_desc[]` (two Iberian street lamps, three polar-circle signs), an SCS data bug.
Unsetting `dynamic_lod_desc[]` and `dynamic_lod_dist[]` removes the warning and changes nothing on screen, since
the LODs were never used. Keeping the LODs instead (`instanced: false`) would drop instancing for every copy.
Decisions: plan world-flash-timing, sub-plan log-fixes.

Every base `def/world/sign*.sii` is scanned, so a game update that adds or fixes such a unit changes the output
(rerun this tool); siiedit fails the build if a listed unit no longer has the keys.

usage: python tools/sign_lods.py [--check]    (--check: fail if world/signs.yaml would change)
Inputs: the extracted base game of this host (profile host file) at the version in megapack.yaml.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILL = pathlib.Path.home() / ".agent-brains/profiles/scs-mod-developer/skills/megapack/scripts"
sys.path.insert(0, str(SKILL))
from megapack import reference_root, repo_game  # noqa: E402

OUT = ROOT / "world" / "signs.yaml"
UNIT = re.compile(r"^sign_model\s*:\s*(\S+)\s*\n\{(.*?)^\}", re.M | re.S)
INSTANCED = re.compile(r"^\s*instanced\s*:\s*true\b", re.M)
LOD_KEYS = ("dynamic_lod_desc[]", "dynamic_lod_dist[]")


def base_dir() -> pathlib.Path:
    mp = yaml.safe_load((ROOT / "megapack.yaml").read_text(encoding="utf-8"))
    base = reference_root(repo_game(ROOT)) / "base" / str(mp["base_game"]["version"])
    if not base.is_dir():
        sys.exit(f"missing extraction {base} — run extract-reference first")
    return base


def scan(base: pathlib.Path) -> dict[str, dict[str, dict]]:
    edits: dict[str, dict[str, dict]] = {}
    for f in sorted((base / "def" / "world").glob("sign*.sii")):
        text = f.read_text(encoding="utf-8", errors="replace")
        for unit, body in UNIT.findall(text):
            if INSTANCED.search(body):
                keys = [k for k in LOD_KEYS if re.search(rf"^\s*{re.escape(k)}\s*:", body, re.M)]
                if keys:
                    edits.setdefault(f.relative_to(base).as_posix(), {})[unit] = {"unset": keys}
    return edits


def render(edits: dict) -> str:
    head = (
        "# GENERATED by tools/sign_lods.py — do not edit by hand; change the script and rerun it.\n"
        "# Instanced base-game signs lose their unused LOD models (the engine warns once per placed copy).\n")
    return head + yaml.safe_dump(edits, sort_keys=False, allow_unicode=True, width=10_000)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    edits = scan(base_dir())
    text = render(edits)
    n = sum(len(u) for u in edits.values())
    if args.check:
        same = OUT.is_file() and OUT.read_text(encoding="utf-8") == text
        print(f"{OUT.relative_to(ROOT)} {'up to date' if same else 'OUT OF DATE'} ({len(edits)} files, {n} units)")
        return 0 if same else 1
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(edits)} files, {n} units")
    return 0


if __name__ == "__main__":
    sys.exit(main())
