#!/usr/bin/env python3
"""
Guards source files World ships whole although they replace a base-game file (the exception to carrying edits).
Such a copy goes stale silently when a game update changes the base file it replaces, so world/whole_files.tsv
records the base file's sha256 at the time the copy was accepted; --check fails when the base file changed (review
the source's copy against the new base, then rerun without --check) or a guarded file is no longer shipped.

  realistic-rain  unit/hookup/vehicle/particle/*rain*.sii   wheel spray; auto-named units (_nameless.*) change
                                                           on every SCS re-export, so edits cannot be pinned

usage: python tools/whole_files.py [--check]
"""
from __future__ import annotations

import argparse
import csv
import fnmatch
import hashlib
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILL = pathlib.Path.home() / ".agent-brains/profiles/ets2-mod-developer/skills/megapack/scripts"
sys.path.insert(0, str(SKILL))
from megapack import host_section  # noqa: E402

OUT = ROOT / "world" / "whole_files.tsv"
GUARDED = [("realistic-rain", "unit/hookup/vehicle/particle/*rain*.sii")]


def rows() -> list[list[str]]:
    ref = pathlib.Path(host_section("Extracted Reference Root")["root"])
    mp = yaml.safe_load((ROOT / "megapack.yaml").read_text(encoding="utf-8"))
    base = ref / "base" / str(mp["base_game"]["version"])
    out = []
    for sid, pattern in GUARDED:
        lock = (ROOT / "lock" / f"{sid}.tsv").read_text(encoding="utf-8").splitlines()
        paths = [r[0] for r in csv.reader(lock, delimiter="\t")
                 if r and not r[0].startswith("#") and r[0] != "path" and fnmatch.fnmatchcase(r[0], pattern)]
        if not paths:
            sys.exit(f"{sid} ships nothing matching {pattern} — update GUARDED")
        for p in sorted(paths):
            b = base / p
            out.append([p, sid, hashlib.sha256(b.read_bytes()).hexdigest() if b.is_file() else "new"])
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = "# GENERATED by tools/whole_files.py — base-game sha256 of the files these whole copies replace.\n" + \
           "path\tsource\tbase_sha256\n" + "".join("\t".join(r) + "\n" for r in rows())
    if args.check:
        same = OUT.is_file() and OUT.read_text(encoding="utf-8") == text
        print(f"{OUT.relative_to(ROOT)} {'up to date' if same else 'OUT OF DATE: review the whole copies against the base'}")
        return 0 if same else 1
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
